// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function StopStreamReply(arg1) {
  return window['go']['bindings']['Assistant']['StopStreamReply'](arg1);
}

export function StreamReply(arg1, arg2) {
  return window['go']['bindings']['Assistant']['StreamReply'](arg1, arg2);
}
