// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ai} from '../models';

export function StopStreamReply(arg1:string):Promise<void>;

export function StreamReply(arg1:Array<ai.Message>,arg2:string):Promise<string>;
