// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1, arg2) {
  return window['go']['bindings']['Document']['Add'](arg1, arg2);
}

export function Choose(arg1) {
  return window['go']['bindings']['Document']['Choose'](arg1);
}

export function Delete(arg1) {
  return window['go']['bindings']['Document']['Delete'](arg1);
}

export function EmbedderState() {
  return window['go']['bindings']['Document']['EmbedderState']();
}

export function Get(arg1) {
  return window['go']['bindings']['Document']['Get'](arg1);
}

export function List(arg1) {
  return window['go']['bindings']['Document']['List'](arg1);
}

export function RefreshIndex() {
  return window['go']['bindings']['Document']['RefreshIndex']();
}
