// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {document} from '../models';

export function Add(arg1:string,arg2:string):Promise<document.CreateDocumentRow>;

export function Choose(arg1:Array<string>):Promise<string>;

export function Delete(arg1:string):Promise<void>;

export function Get(arg1:string):Promise<document.GetDocumentRow>;

export function List(arg1:string):Promise<Array<document.ListDocumentsRow>>;
