// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function StopStreamReply(arg1:string):Promise<void>;

export function StreamReply(arg1:string):Promise<string>;
