// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {message} from '../models';

export function Create(arg1:string,arg2:string,arg3:string):Promise<message.Message>;

export function Get(arg1:string):Promise<message.Message>;

export function List(arg1:string):Promise<Array<message.Message>>;
