// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bindings} from '../models';

export function ChangeThemeAccent(arg1:string):Promise<void>;

export function ChangeThemeMode(arg1:string):Promise<void>;

export function ChangeWorkspace(arg1:string):Promise<void>;

export function GetModelSettings():Promise<bindings.ModelSettings>;

export function GetThemeSettings():Promise<bindings.ThemeSettings>;

export function ListModels(arg1:string,arg2:string):Promise<Array<string>>;

export function SaveModelSettings(arg1:bindings.ModelSettings):Promise<void>;

export function SelectedWorkspace():Promise<string>;
