// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeWorkspace(arg1) {
  return window['go']['bindings']['Settings']['ChangeWorkspace'](arg1);
}

export function GetModelSettings() {
  return window['go']['bindings']['Settings']['GetModelSettings']();
}

export function ListModels(arg1, arg2) {
  return window['go']['bindings']['Settings']['ListModels'](arg1, arg2);
}

export function SaveModelSettings(arg1) {
  return window['go']['bindings']['Settings']['SaveModelSettings'](arg1);
}

export function SelectedWorkspace() {
  return window['go']['bindings']['Settings']['SelectedWorkspace']();
}
