// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bindings} from '../models';

export function GetModelSettings():Promise<bindings.ModelSettings>;

export function ListModels(arg1:string,arg2:string):Promise<Array<string>>;

export function SaveModelSettings(arg1:bindings.ModelSettings):Promise<void>;
