// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoRename(arg1, arg2) {
  return window['go']['bindings']['Thread']['AutoRename'](arg1, arg2);
}

export function Create(arg1, arg2) {
  return window['go']['bindings']['Thread']['Create'](arg1, arg2);
}

export function Delete(arg1) {
  return window['go']['bindings']['Thread']['Delete'](arg1);
}

export function Get(arg1) {
  return window['go']['bindings']['Thread']['Get'](arg1);
}

export function List(arg1) {
  return window['go']['bindings']['Thread']['List'](arg1);
}

export function Rename(arg1, arg2) {
  return window['go']['bindings']['Thread']['Rename'](arg1, arg2);
}
