// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {thread} from '../models';

export function AutoRename(arg1:string,arg2:string):Promise<thread.Thread>;

export function Create(arg1:string,arg2:string):Promise<thread.Thread>;

export function Delete(arg1:string):Promise<void>;

export function Get(arg1:string):Promise<thread.Thread>;

export function List(arg1:string):Promise<Array<thread.Thread>>;

export function Rename(arg1:string,arg2:string):Promise<thread.Thread>;
