// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {workspace} from '../models';

export function Create(arg1:string):Promise<workspace.Workspace>;

export function Delete(arg1:string):Promise<void>;

export function Get(arg1:string):Promise<workspace.Workspace>;

export function List():Promise<Array<workspace.Workspace>>;

export function Rename(arg1:string,arg2:string):Promise<workspace.Workspace>;
