// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['bindings']['Workspace']['Create'](arg1);
}

export function Delete(arg1) {
  return window['go']['bindings']['Workspace']['Delete'](arg1);
}

export function Get(arg1) {
  return window['go']['bindings']['Workspace']['Get'](arg1);
}

export function List() {
  return window['go']['bindings']['Workspace']['List']();
}

export function Rename(arg1, arg2) {
  return window['go']['bindings']['Workspace']['Rename'](arg1, arg2);
}
