package ai

import "context"

type Message struct {
	Content string
	Role    string
}

type Chunk struct {
	Delta string
	Role  string
}

type Embedding struct {
	Vector  []float64
	Index   int
	Content string
}

type LLM interface {
	// Chat returns the complete [Message] generated by the model or any [error].
	Chat(
		ctx context.Context,
		model string,
		conversation []Message,
	) (Message, error)

	// Stream returns the [Chunk] channel to stream model completions and also an [error] channel. Note that each subsequent [Chunk] has new completion delta appended to the completion delta of the previous [Chunk].
	Stream(
		ctx context.Context,
		model string,
		conversation []Message,
	) (<-chan Chunk, <-chan error)

	// Embedding returns the vector embeddings generated by the model for the content or any [error].
	Embedding(
		ctx context.Context,
		embeddingModel string,
		content string,
	) ([]Embedding, error)
}
