// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package thread

import (
	"context"
)

type Querier interface {
	CreateThread(ctx context.Context, arg CreateThreadParams) (Thread, error)
	DeleteThread(ctx context.Context, id string) error
	GetThread(ctx context.Context, id string) (Thread, error)
	ListThreads(ctx context.Context, workspace string) ([]Thread, error)
	UpdateThread(ctx context.Context, arg UpdateThreadParams) (Thread, error)
}

var _ Querier = (*Queries)(nil)
