// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: thread.sql

package thread

import (
	"context"
)

const createThread = `-- name: CreateThread :one
INSERT INTO threads (
    id, title, workspace, created
) VALUES (
    ?, ?, ?, ?
) RETURNING id, title, workspace, created
`

type CreateThreadParams struct {
	ID        string
	Title     string
	Workspace string
	Created   string
}

func (q *Queries) CreateThread(ctx context.Context, arg CreateThreadParams) (Thread, error) {
	row := q.db.QueryRowContext(ctx, createThread,
		arg.ID,
		arg.Title,
		arg.Workspace,
		arg.Created,
	)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Workspace,
		&i.Created,
	)
	return i, err
}

const deleteThread = `-- name: DeleteThread :exec
DELETE FROM threads WHERE id = ?
`

func (q *Queries) DeleteThread(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteThread, id)
	return err
}

const getThread = `-- name: GetThread :one
SELECT id, title, workspace, created FROM threads WHERE id = ? LIMIT 1
`

func (q *Queries) GetThread(ctx context.Context, id string) (Thread, error) {
	row := q.db.QueryRowContext(ctx, getThread, id)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Workspace,
		&i.Created,
	)
	return i, err
}

const listThreads = `-- name: ListThreads :many
SELECT id, title, workspace, created FROM threads WHERE workspace = ? ORDER BY created DESC
`

func (q *Queries) ListThreads(ctx context.Context, workspace string) ([]Thread, error) {
	rows, err := q.db.QueryContext(ctx, listThreads, workspace)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Thread
	for rows.Next() {
		var i Thread
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Workspace,
			&i.Created,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateThread = `-- name: UpdateThread :one
UPDATE threads SET title = ? WHERE id = ? RETURNING id, title, workspace, created
`

type UpdateThreadParams struct {
	Title string
	ID    string
}

func (q *Queries) UpdateThread(ctx context.Context, arg UpdateThreadParams) (Thread, error) {
	row := q.db.QueryRowContext(ctx, updateThread, arg.Title, arg.ID)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Workspace,
		&i.Created,
	)
	return i, err
}
