// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: message.queries.sql

package message

import (
	"context"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (
    id, role, content, thread, created
) VALUES (
    ?, ?, ?, ?, ?
) RETURNING id, role, content, thread, created
`

type CreateMessageParams struct {
	ID      string
	Role    string
	Content string
	Thread  string
	Created string
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessage,
		arg.ID,
		arg.Role,
		arg.Content,
		arg.Thread,
		arg.Created,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Content,
		&i.Thread,
		&i.Created,
	)
	return i, err
}

const getMessage = `-- name: GetMessage :one
SELECT id, role, content, thread, created FROM messages WHERE id = ? LIMIT 1
`

func (q *Queries) GetMessage(ctx context.Context, id string) (Message, error) {
	row := q.db.QueryRowContext(ctx, getMessage, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Content,
		&i.Thread,
		&i.Created,
	)
	return i, err
}

const listMessages = `-- name: ListMessages :many
SELECT id, role, content, thread, created FROM messages WHERE thread = ? ORDER BY created DESC
`

func (q *Queries) ListMessages(ctx context.Context, thread string) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listMessages, thread)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.Content,
			&i.Thread,
			&i.Created,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
