// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package message

import (
	"context"
)

type Querier interface {
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	GetMessage(ctx context.Context, id string) (Message, error)
	ListMessages(ctx context.Context, thread string) ([]Message, error)
}

var _ Querier = (*Queries)(nil)
