// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package workspace

type Workspace struct {
	ID        string
	Name      string
	Candelete bool
	Canrename bool
	Created   string
}
