// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspace.sql

package workspace

import (
	"context"
)

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (
    id, name, canDelete, canRename, created
) VALUES (
    ?, ?, ?, ?, ?
)
RETURNING id, name, candelete, canrename, created
`

type CreateWorkspaceParams struct {
	ID        string
	Name      string
	Candelete bool
	Canrename bool
	Created   string
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, createWorkspace,
		arg.ID,
		arg.Name,
		arg.Candelete,
		arg.Canrename,
		arg.Created,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Candelete,
		&i.Canrename,
		&i.Created,
	)
	return i, err
}

const deleteWorkspace = `-- name: DeleteWorkspace :exec
DELETE FROM workspaces WHERE id = ?
`

func (q *Queries) DeleteWorkspace(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteWorkspace, id)
	return err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT id, name, candelete, canrename, created FROM workspaces WHERE id = ? LIMIT 1
`

func (q *Queries) GetWorkspace(ctx context.Context, id string) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, getWorkspace, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Candelete,
		&i.Canrename,
		&i.Created,
	)
	return i, err
}

const listWorkspaces = `-- name: ListWorkspaces :many
SELECT id, name, candelete, canrename, created FROM workspaces ORDER BY created DESC
`

func (q *Queries) ListWorkspaces(ctx context.Context) ([]Workspace, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workspace
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Candelete,
			&i.Canrename,
			&i.Created,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkspace = `-- name: UpdateWorkspace :one
UPDATE workspaces SET name = ? WHERE id = ?
RETURNING id, name, candelete, canrename, created
`

type UpdateWorkspaceParams struct {
	Name string
	ID   string
}

func (q *Queries) UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, updateWorkspace, arg.Name, arg.ID)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Candelete,
		&i.Canrename,
		&i.Created,
	)
	return i, err
}
