// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: document.sql

package document

import (
	"context"
)

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (
    id, title, extension, embedid, content, workspace, created
) VALUES (
    ?, ?, ?, ?, ?, ?, ?
) RETURNING id, title, extension, embedid, indexed, workspace, created
`

type CreateDocumentParams struct {
	ID        string
	Title     string
	Extension string
	Embedid   string
	Content   []byte
	Workspace string
	Created   string
}

type CreateDocumentRow struct {
	ID        string
	Title     string
	Extension string
	Embedid   string
	Indexed   bool
	Workspace string
	Created   string
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (CreateDocumentRow, error) {
	row := q.db.QueryRowContext(ctx, createDocument,
		arg.ID,
		arg.Title,
		arg.Extension,
		arg.Embedid,
		arg.Content,
		arg.Workspace,
		arg.Created,
	)
	var i CreateDocumentRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Extension,
		&i.Embedid,
		&i.Indexed,
		&i.Workspace,
		&i.Created,
	)
	return i, err
}

const deleteDocument = `-- name: DeleteDocument :exec
DELETE FROM documents WHERE id = ?
`

func (q *Queries) DeleteDocument(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteDocument, id)
	return err
}

const getDocument = `-- name: GetDocument :one
SELECT id, title, extension, embedid, indexed, workspace, created
FROM documents
WHERE id = ? LIMIT 1
`

type GetDocumentRow struct {
	ID        string
	Title     string
	Extension string
	Embedid   string
	Indexed   bool
	Workspace string
	Created   string
}

func (q *Queries) GetDocument(ctx context.Context, id string) (GetDocumentRow, error) {
	row := q.db.QueryRowContext(ctx, getDocument, id)
	var i GetDocumentRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Extension,
		&i.Embedid,
		&i.Indexed,
		&i.Workspace,
		&i.Created,
	)
	return i, err
}

const getDocumentContent = `-- name: GetDocumentContent :one
SELECT content FROM documents WHERE id = ? LIMIT 1
`

func (q *Queries) GetDocumentContent(ctx context.Context, id string) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getDocumentContent, id)
	var content []byte
	err := row.Scan(&content)
	return content, err
}

const listDocuments = `-- name: ListDocuments :many
SELECT id, title, extension, embedid, indexed, workspace, created
FROM documents WHERE workspace = ?
ORDER BY created DESC
`

type ListDocumentsRow struct {
	ID        string
	Title     string
	Extension string
	Embedid   string
	Indexed   bool
	Workspace string
	Created   string
}

func (q *Queries) ListDocuments(ctx context.Context, workspace string) ([]ListDocumentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDocuments, workspace)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDocumentsRow
	for rows.Next() {
		var i ListDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Extension,
			&i.Embedid,
			&i.Indexed,
			&i.Workspace,
			&i.Created,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocument = `-- name: UpdateDocument :one
UPDATE documents
SET title = ?, extension = ?, indexed = ?,  content = ?
WHERE id = ?
RETURNING id, title, extension, embedid, indexed, workspace, created
`

type UpdateDocumentParams struct {
	Title     string
	Extension string
	Indexed   bool
	Content   []byte
	ID        string
}

type UpdateDocumentRow struct {
	ID        string
	Title     string
	Extension string
	Embedid   string
	Indexed   bool
	Workspace string
	Created   string
}

func (q *Queries) UpdateDocument(ctx context.Context, arg UpdateDocumentParams) (UpdateDocumentRow, error) {
	row := q.db.QueryRowContext(ctx, updateDocument,
		arg.Title,
		arg.Extension,
		arg.Indexed,
		arg.Content,
		arg.ID,
	)
	var i UpdateDocumentRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Extension,
		&i.Embedid,
		&i.Indexed,
		&i.Workspace,
		&i.Created,
	)
	return i, err
}
