// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package document

type Document struct {
	ID        string
	Title     string
	Extension string
	Content   []byte
	Workspace string
	Created   string
}
