// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package document

type Document struct {
	ID        string
	Title     string
	Extension string
	Content   []byte
	Workspace string
	Created   string
}

type Message struct {
	ID      string
	Role    string
	Content string
	Thread  string
	Created string
}

type Thread struct {
	ID        string
	Title     string
	Workspace string
	Created   string
}

type Workspace struct {
	ID        string
	Name      string
	Candelete bool
	Canrename bool
	Created   string
}
