// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package document

import (
	"context"
)

type Querier interface {
	CreateDocument(ctx context.Context, arg CreateDocumentParams) (CreateDocumentRow, error)
	DeleteDocument(ctx context.Context, id string) error
	GetDocument(ctx context.Context, id string) (GetDocumentRow, error)
	GetDocumentContent(ctx context.Context, id string) ([]byte, error)
	GetDocumentIDsToIndex(ctx context.Context) ([]string, error)
	GetDocumentPlainText(ctx context.Context, id string) (string, error)
	ListDocuments(ctx context.Context, workspace string) ([]ListDocumentsRow, error)
	MarkDocumentAsIndexed(ctx context.Context, id string) error
	UpdateDocument(ctx context.Context, arg UpdateDocumentParams) (UpdateDocumentRow, error)
}

var _ Querier = (*Queries)(nil)
