// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Build() {
  return window['go']['main']['BuildInfo']['Build']();
}

export function Version() {
  return window['go']['main']['BuildInfo']['Version']();
}
